[package]
name = "hermod-dummy"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
hermod-module = { path = "../../module" }
